options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build"
    args:
      - "build"
      - "-t"
      - "${_IMAGE}"
      - "-f"
      - "server/Dockerfile"
      - "server"

  - name: "gcr.io/cloud-builders/docker"
    id: "Push"
    args:
      - "push"
      - "${_IMAGE}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "skellypings"
      - "--image"
      - "${_IMAGE}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "SKELLYPINGS_SECRET=${_SKELLYPINGS_SECRET},BACKUP_BUCKET=${_BACKUP_BUCKET},FIRESTORE_COLLECTION=telemetry_events"
      - "--memory"
      - "256Mi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "1"

substitutions:
  _REGION: "northamerica-northeast1"
  _IMAGE: "gcr.io/${PROJECT_ID}/skellypings:${COMMIT_SHA}"
  _SKELLYPINGS_SECRET: ""
  _BACKUP_BUCKET: ""

images:
  - "${_IMAGE}"
